### ISSUE TITLE
Allow custom PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by TibboddiT** [miracle-wm-org/miracle-wm#196]
To build miracle, I first build mir locally because I'm not an Ubuntu user and mir libs packaged with my system are too old (and I generally prefer build everything myself).

I therefore need to customize `PKG_CONFIG_PATH` so that the local mir libs can be found.

In the CmakeLists.txt provided there is [this line](https://github.com/mattkae/miracle-wm/blob/develop/CMakeLists.txt#L11C1-L11C54):

```sh
set(ENV{PKG_CONFIG_PATH} "/usr/local/lib/pkgconfig/")
```

Currently I manually replace this line to have a fully working build phase:

```patch
-set(ENV{PKG_CONFIG_PATH} "/usr/local/lib/pkgconfig/")
+set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:/usr/local/lib/pkgconfig/")
```

and I export a custom `PKG_CONFIG_PATH` before building:

```sh
export PKG_CONFIG_PATH="${BASE_DIR}/mir/install/lib/pkgconfig/:$PKG_CONFIG_PATH"
export LD_LIBRARY_PATH="${BASE_DIR}/mir/install/lib:${LD_LIBRARY_PATH}"
```

(`BASE_DIR/mir/install` being the install dir of the local mir build)

I'm not a CMake specialist, so I was wondering: is there a way of using a local mir build without modifying the miracle-wm upstream files ?

If not, and if the fix I currently use is acceptable, I can make a PR.

**Comment by mattkae** [comment]
Hiya @TibboddiT :wave: 
Thanks for filing the bug. I think that I would prefer a cmake build option instead if you'd like to take a try at it. An example is the `SNAP_BUILD` option that you can find [here](https://github.com/mattkae/miracle-wm/blob/92c5c6784f00cce6f290572832191b43169432eb/CMakeLists.txt#L16).

I would definitely appreciate if you opened the PR for this one :smile:

**Comment by TibboddiT** [comment]
See #198 :wink:
